const categories = {
  FOOD: "Food",
  DRINKS: "Drinks",
  ART: "Art",
  CULTURE: "Culture",
  NATURE: "Nature",
  EVENTS: "Events"
};

const articles = [
  {
    id: "festa-delle-lanterne",
    title: "Festa Delle Lanterne",
    image: "festa-delle-lanterne.jpg",
    subtitle: "The festival of dragons.",
    category: categories.EVENTS,
    date: new Date("22/07/2019"),
    author: "Bilyana Georgieva",
    hours: ["Changes every year"],
    prices: ["FREE"],
    website: "articles.html?name=festa-delle-lanterne",
    maps: "https://goo.gl/maps/TtEbYMbTTZgqvbBR6",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g187849-d1925887-Reviews-Chinatown-Milan_Lombardy.html",
    featured: true,
    content: "In the days of the Chinese New Year, the Paolo Sarpi district is a \"mobile party.\"  Chinatown is colored red with festoons, ribbons and lanterns and parades of acrobats and masks continue all the time.  And then there are also concerts, screenings, fireworks and the ever-present march of dragons.  Also called Spring Festival, the Chun Jie is among the most heartfelt celebrations for the Chinese community of Milan and is spent with family, with gifts and dinner, a bit like our Christmas.  The festivities last about two weeks and culminate with the Lantern Festival when every Chinese lights candles on the windows and walks around the neighborhood holding colorful lanterns to guide benevolent spirits.  Pay attention to the dates: the party follows lunar cycles and varies every year.",
  },
  {
    id: "villa-belgoiojoso-bonaparte",
    title: "Villa Belgoiojoso Bonaparte",
    image: "villa-belgoiojoso-bonaparte.jpg",
    subtitle: "Enchanting world for the small ones",
    category: categories.NATURE,
    date: new Date("19/01/2019"),
    author: "Bilyana Georgieva",
    hours: ["Tuesday-Sunday:  9.00 - 17.00", "Monday: OFF"],
    prices: ["FREE"],
    website: "http://www.gam-milano.com/it/la-villa/",
    maps: "https://goo.gl/maps/A4yoQSLSW4QJnUud9",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g635872-d2369006-Reviews-Villa_Reale-Monza_Province_of_Monza_and_Brianza_Lombardy.html",
    featured: false,
    content: "In the garden of Villa Belgiojoso Bonaparte there are small temples, sculptures of modern art, pagodas, ancient ruins and an artificial lake designed so as never to allow a unified view, so as to influence the imagination of the observer.  Admission is restricted to children under 12 and adults in their company.",
  },
  {
    id: "villa-necchi-campiglio",
    title: "Villa Necchi Campiglio",
    image: "villa-necchi-campiglio.jpg",
    subtitle:  "A Thirties icon in the heart of Milan",
    category: categories.ART,
    date: new Date("12/12/2015"),
    author: "Bilyana Georgieva",
    hours: ["Monday-Sunday:  10.00 - 18.00"],
    prices: ["FREE with FAI subscription"],
    website: "https://www.fondoambiente.it/luoghi/villa-necchi-campiglio",
    maps: "https://g.page/villa-necchi-campiglio?share",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g187849-d1930515-Reviews-Villa_Necchi_Campiglio-Milan_Lombardy.html",
    featured: false,
    content: "Villa Necchi Campiglio, in is a property of FAI and was built by Pietro Portaluppi between 1932 and 1935 for the Necchi Campiglio family, from the Lombardian industrial bourgeoisie. The villa in 2010 was used as a film set for the movie \"Io sono l'amore\" with Tilda Swinton. It is also home of privately donated famous collections of significant pieces of the 20th-century Italian art. A great occasion to visit it for free accompanied by thoughtful and highly trained FAI volunteers is to take part in the conferences and presentations that often take part inside. You could also visit one of the \"Gioirnate del FAI\" like their annual spring one for example. Anyways the visit to the villa is always free!"
    },
  {
    id: "san-bernadino-alle-ossa",
    title: "San Bernadino Alle Ossa",
    image: "san-bernadino-alle-ossa.jpg",
    subtitle:
      "",
    category: categories.CULTURE,
    date: new Date("12/12/2019"),
    author: "Bilyana Georgieva",
    hours: [""],
    prices: ["FREE"],
    website: "",
    maps: "",
    tripAdvisor: "",
    featured: false,
    content:
      ""
  },
  {
    id: "salsamenteria-di-parma",
    title: "Salsamenteria Di Parma",
    image: "salsamenteria-di-parma.jpeg",
    subtitle:
      "Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.",
    category: categories.FOOD,
    date: new Date("12/12/2019"),
    author: "Bilyana Georgieva",
    hours: [""],
    prices: ["FREE"],
    website: "",
    maps: "",
    tripAdvisor: "",
    featured: false,
    content:
      ""
  },
  {
    id: "pizzeria-da-biagio",
    title: "Pizzeria Da Biagio",
    image: "pizzeria-da-biagio.jpeg",
    subtitle:
      "Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.",
    category: categories.FOOD,
    date: new Date("12/12/2017"),
    author: "Bilyana Georgieva",
    hours: [""],
    prices: ["FREE"],
    website: "",
    maps: "",
    tripAdvisor: "",
    featured: true,
    content:
      ""
  },
  {
    id: "orto-botanico-di-brera",
    title: "Orto Botanico Di Brera",
    image: "orto-botanico-di-brera.jpg",
    subtitle: "The secret garden",
    category: categories.NATURE,
    date: new Date("04/06/2019"),
    author: "Bilyana Georgieva",
    hours: ["Monday-Saturday:  10.00 - 18.00", "Sunday: OFF"],
    prices: ["FREE"],
    website: "http://www.ortobotanicoitalia.it/lombardia/brera/",
    maps: "https://goo.gl/maps/QyngLw4zyUGXARxw8",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g187849-d2078633-Reviews-Orto_Botanico_di_Brera-Milan_Lombardy.html",
    featured: false,
    content: "In the heart of Milan, there is a magnificent garden, hidden in one of the most beautiful buildings. This is the Botanical Garden of Brera, which is a home of more than 3,000 plant species and a greenhouse designed by Piermarini. Among the goodies, there are two centuries-old Ginko Biloba, among the oldest in Europe, a 40-meter high linden and a forest of medicinal plants. Ideal for a romantic date, to get there you have to cross the labyrinth of corridors of the Academy or take the shortcut and enter directly from via Fiori Oscuri 4. Perhaps to preserve the charm of the place, bizarre opening times have been chosen: you can visit it for free every day, but unfortunately never on a Sunday. Few frequent it, many ignore its existence: it is the secret garden of the Milanese."
  },
  {
    id: "mercatino-dell-usato",
    title: "Mercatino Dell'usato",
    image: "mercatino-dell-usato.jpg",
    subtitle:
      "Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.",
    category: categories.CULTURE,
    date: new Date("12/12/2013"),
    author: "Bilyana Georgieva",
    hours: [""],
    prices: ["FREE"],
    website: "",
    maps: "",
    tripAdvisor: "",
    featured: false,
    content:
      ""
  },
  {
    id: "galleria-darte-moderna",
    title: "Galleria d'Arte Moderna",
    image: "galleria-darte-moderna.jpg",
    subtitle: "A gallery of excellence.",
    category: categories.ART,
    date: new Date("17/04/2019"),
    author: "Bilyana Georgieva",
    hours: ["Tuesday-Friday:  9.00 - 17.30", "Monday: OFF"],
    prices: ["FREE"],
    website: "http://www.gam-milano.com/it/home/",
    maps: "https://goo.gl/maps/ck6FaA6HW4193HoM6",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g187849-d243404-Reviews-Galleria_Civica_d_Arte_Moderna-Milan_Lombardy.html",
    featured: false,
    content: "Entrance is always free at the Modern Art Gallery.  The museum is located in a magnificent villa built between 1790 and 1796 by Count Barbiano di Belgiojoso.  Passed into the hands of the French, it became the residence of the governor of Milan Gioacchino Murat, who made it the sumptuous setting of lunches and dance parties.  In 1804 Melzi d'Eril gave it to Napoleon, and since then it is known as \"Villa Bonaparte.\"  After the abandonment following the unification of Italy, the villa was restored by the Municipality of Milan and, starting from 1921 became the headquarters of the Modern Art Gallery of Milan.  With its two thousand paintings and seven hundred sculptures, it is the Museum of the nineteenth century for excellence and testifies to the evolution of style from neoclassicism to divisionism.  Here you can admire works by masters such as Appiani and Segantini, passing through Hayez, Medardo Rosso and Previati.  In addition to the Grassi collection, with the Italian and French nineteenth-century canvases on the ground floor, you can visit the Vismara collection, which contains masterpieces by Modigliani, De Pisis, Carrà, Morandi, Sironi, Picasso, Matisse, Renoir.",
    },
  {
    id: "civico-planetario-hoepli",
    title: "Civico Planetario Hoepli",
    image: "civico-planetario-hoepli.jpg",
    subtitle: "Admire the stars",
    category: categories.CULTURE,
    date: new Date("14/03/2019"),
    author: "Bilyana Georgieva",
    hours: ["Monday-Friday:  9.00 - 17.00", "Saturday - Sunday: 14.15 - 17.30"],
    prices: ["3 euro"],
    website: "https://lofficina.eu/",
    maps: "https://goo.gl/maps/Wqrt4zUVAmAPaoRL9",
    tripAdvisor: "https://www.tripadvisor.it/Attraction_Review-g187849-d1912625-Reviews-Civico_Planetario_Ulrico_Hoepli-Milan_Lombardy.html",
    featured: false,
    content: "If you can barely spot the Big Dipper, it's time to head to the Hoepli Civic Planetarium.  Located in the gardens of Porta Venezia, it was inaugurated in 1930. The project, designed by architect Piero Portaluppi, was commissioned by the Swiss publisher Ulrico Hoepli, who donated it to the city.  The Planetarium is one of the largest in Italy (19.6 meters in diameter, with a capacity of 375 seats) and the entrance ticket costs 3 euros.  Here are organized guided observations of the sky, generally held every Saturday and Sunday afternoon (15:00 and 16:30) and the first evening of activity each month is celebrated with the identification of the main constellations and basic astronomical phenomena.  They are suitable for newcomers to the sky, for those approaching astronomy for the first time or for those who want to admire the spectacle of the starry sky.",
  },
  {
    id: "bar-anny",
    title: "Bar Anny",
    image: "bar-anny.jpg",
    subtitle: "Go back to the 80's",
    category: categories.DRINKS,
    date: new Date("18/06/2019"),
    author: "Bilyana Georgieva",
    hours: [""],
    prices: ["Varies"],
    website: "articles.html?name=bar-anny",
    maps: "https://goo.gl/maps/oQAZWvuTtZJhY2KS7",
    tripAdvisor: "https://www.tripadvisor.it/Restaurant_Review-g187849-d13803761-Reviews-Bar_Anny-Milan_Lombardy.html",
    featured: true,
    content: "Bar Anny in via De Togni was a cult in the eighties.  Upon entering, there is only a counter on the right and a table with a brown leather horseshoe-shaped sofa, while upstairs, there is a small dining room.  Here you will find excellent sandwiches at competitive prices (around 3.50 euros) compared to the other bars in the area.  The students and professors of the nearby Catholic University know this well.",
  }
];